# Generated by Django 3.1.4 on 2021-11-17 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snack',
            name='image',
            field=models.ImageField(default=None, height_field=200, upload_to='', width_field=200),
        ),
    ]
