# Generated by Django 3.1.4 on 2021-11-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0003_auto_20211117_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
