# Generated by Django 3.1.4 on 2021-11-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0004_auto_20211117_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='image',
            field=models.ImageField(upload_to=None),
        ),
    ]
