# Generated by Django 3.1.4 on 2021-11-17 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0005_auto_20211117_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snack',
            name='image',
        ),
    ]
